In [2]:
set1:set = {1,1,3,3,5,8,7,9,10}
set1.add(11)
set1

{1, 3, 5, 7, 8, 9, 10, 11}

In [2]:
import numpy as np
array1 = np.array(range(1,11)) #要檢查datatype需要先用變數接收，因為單只有np.array(range(1,11))是不會傳出東西的

#陣列運算
array1 + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
np.arange(1.3,3.5,0.1)

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

In [4]:
display(np.arange(1.3,3.5,0.1)) #這是jupyter notebook提供的方法

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

In [5]:
display(np.linspace(1,2,20))

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [12]:
display(np.random.random())
display(np.random.randn(10)) #常態分佈亂數-1~1 / standard normal distribution
display(np.random.randn(10,5))
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.6899916138272719

array([-0.37490238,  0.21945656,  0.62744062, -1.16050386, -0.08086837,
        1.81461665, -0.64363164, -0.83426438,  0.23479834, -0.2958215 ])

array([[-0.46827189, -2.01559516, -0.61304123, -0.2936491 ,  0.88334152],
       [-0.58676358,  1.41502693,  1.502939  , -2.40759707,  0.17167477],
       [-0.96431334, -1.37234893, -1.19808001,  0.94467649,  0.65474508],
       [-0.68621602,  1.93360525, -0.41379609,  0.76110254, -1.08357325],
       [ 1.23980252, -1.86290817, -1.41434172, -0.60920026,  0.20868564],
       [ 1.03693536,  0.99198951, -0.68902723, -0.75464665, -0.67146119],
       [-0.06745151, -0.66663244,  0.27133335,  1.05606225,  1.86725428],
       [ 0.68720452, -0.66950876, -1.50228845, -2.0514026 , -0.22019439],
       [-1.09435602,  1.36375202, -0.55840458, -0.63703751,  0.12240641],
       [-1.23005945,  1.37174169,  0.0522457 , -0.44353021,  0.23167859]])

array([[[ 1.0287248 ,  0.02604302,  1.20954315],
        [ 0.85518128,  0.58653399,  0.13119881],
        [ 0.10210699,  0.32259446,  0.20016493],
        [ 0.17108156, -2.87339002, -0.86613854],
        [-0.79356754, -0.77740768,  0.30290921]],

       [[ 0.23653231, -0.14766646,  0.51076583],
        [ 2.06034828, -0.27449226, -0.12429062],
        [ 0.39097841,  0.57143714, -0.22612039],
        [ 0.62824471, -1.14914303, -2.251029  ],
        [ 1.55577547,  0.18308996,  0.80899328]],

       [[-0.2037264 , -0.00956667, -0.75201285],
        [ 2.04946776, -2.51857092,  0.47799033],
        [ 0.97012894,  1.15966433,  0.05950668],
        [-0.42217077, -1.68498808,  1.70846163],
        [-1.45517228, -1.95154471,  0.08525451]],

       [[ 0.8684551 , -0.08809237, -0.37919011],
        [-0.63536794, -2.12091228, -0.39430287],
        [ 0.47154514,  0.99623504,  0.83519811],
        [ 0.08473883,  0.05334103,  0.96653907],
        [ 1.44639551, -0.4730795 , -2.23174775]],

       [[-1.

array([[8, 6, 6, 7, 2],
       [2, 2, 8, 8, 9],
       [9, 7, 8, 3, 7],
       [3, 4, 6, 1, 3],
       [3, 9, 7, 9, 3],
       [9, 1, 3, 1, 7],
       [9, 3, 4, 8, 9],
       [6, 8, 2, 3, 6],
       [4, 2, 8, 9, 4],
       [8, 2, 1, 9, 1]])