In [1]:

# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/home/codespace/.local/lib/python3.10/site-packages/numpy/__init__.py'>
1.24.3


In [2]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:

print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('data: ', a.data)

ndim:  2
shape:  (3, 5)
size:  15
dtype:  int64
itemsize:  8
data:  <memory at 0x7f75dd1e6e90>


In [4]:
# List 與 Array 的轉換

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [5]:
b = np.arange(12)

In [6]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
list(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [8]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
list(b.reshape(3,4))

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [10]:
type(list(b.reshape(3,4)))

list

In [11]:
(b.reshape(3,4)).tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [12]:
b = np.random.randint(10, size=(3,4)) 

In [13]:
print(f'印出的結果:\n {b}')
print(f'陣列的維度:ndim → {b.ndim}')
print(f'陣列的維度大小:shape → {b.shape}')
print(f'陣列中的元素個數:size → {b.size}')
print(f'陣列中的資料型態:dtype → {b.dtype}')
print(f'陣列中的元素占用空間: itemsize → {b.itemsize}')
print(f'陣列的長度: length → {len(b)}')
print(f'陣列的類型: type → {type(b)}')

印出的結果:
 [[2 4 6 0]
 [3 6 4 3]
 [5 3 7 8]]
陣列的維度:ndim → 2
陣列的維度大小:shape → (3, 4)
陣列中的元素個數:size → 12
陣列中的資料型態:dtype → int64
陣列中的元素占用空間: itemsize → 8
陣列的長度: length → 3
陣列的類型: type → <class 'numpy.ndarray'>


In [14]:
c = np.random.randint(10, size=(2,3,2)) 

print(f'印出的結果:\n {c}')
print(f'陣列的維度:ndim → {c.ndim}')
print(f'陣列的維度大小:shape → {c.shape}')
print(f'陣列中的元素個數:size → {c.size}')
print(f'陣列中的資料型態:dtype → {c.dtype}')
print(f'陣列中的元素占用空間: itemsize → {c.itemsize}')
print(f'陣列的長度: length → {len(c)}')
print(f'陣列的類型: type → {type(c)}')

印出的結果:
 [[[6 6]
  [6 4]
  [2 5]]

 [[9 2]
  [7 8]
  [2 8]]]
陣列的維度:ndim → 3
陣列的維度大小:shape → (2, 3, 2)
陣列中的元素個數:size → 12
陣列中的資料型態:dtype → int64
陣列中的元素占用空間: itemsize → 8
陣列的長度: length → 2
陣列的類型: type → <class 'numpy.ndarray'>


In [16]:
#如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
import numpy as np
a = np.random.randint(100, size = 6)
print(list(a))
print(a.tolist())

[91, 49, 97, 50, 0, 67]
[91, 49, 97, 50, 0, 67]


In [18]:
print(type(list(a)))
print(type(a.tolist()))

<class 'list'>
<class 'list'>


In [19]:
b = np.random.randint(100, size = (3,4))

In [20]:
print(list(b))

[array([25,  8, 24, 83]), array([22, 20, 99,  2]), array([ 2, 12, 37, 15])]


In [21]:
type(list(b))

list

In [22]:
b.tolist

<function ndarray.tolist>

In [24]:
print(b.tolist())

[[25, 8, 24, 83], [22, 20, 99, 2], [2, 12, 37, 15]]


In [25]:
c = np.random.randint(100, size = (2,3,4))

In [26]:
print(list(c))

[array([[28, 35, 39,  7],
       [ 4, 87, 17, 25],
       [83, 25, 13, 97]]), array([[26, 58, 47, 90],
       [58, 73,  6, 79],
       [18, 63,  3, 88]])]


In [27]:
print(c.tolist())

[[[28, 35, 39, 7], [4, 87, 17, 25], [83, 25, 13, 97]], [[26, 58, 47, 90], [58, 73, 6, 79], [18, 63, 3, 88]]]


In [28]:
print(a)

[91 49 97 50  0 67]


In [29]:
print(b)

[[25  8 24 83]
 [22 20 99  2]
 [ 2 12 37 15]]


In [30]:
print(c)

[[[28 35 39  7]
  [ 4 87 17 25]
  [83 25 13 97]]

 [[26 58 47 90]
  [58 73  6 79]
  [18 63  3 88]]]


In [31]:
def tolist(iterable):#by 遞迴+for迴圈
    #判斷是不是陣列
    if type(iterable) !=np.ndarray:
        return iterable
    
    newData=[]#給一個新的陣列
    for i in iterable:
        newData.append(tolist(i))
        #顯示程式如何轉 print(newData)
    return newData
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[91, 49, 97, 50, 0, 67]
[[25, 8, 24, 83], [22, 20, 99, 2], [2, 12, 37, 15]]
[[[28, 35, 39, 7], [4, 87, 17, 25], [83, 25, 13, 97]], [[26, 58, 47, 90], [58, 73, 6, 79], [18, 63, 3, 88]]]


In [4]:
import numpy as np
a = np.random.randint(10, size = 6)

In [5]:
print(f"印出的結果:\n {a}")

印出的結果:
 [0 7 0 3 7 8]


In [6]:
print(f"陣列的維度: {a.ndim}")

陣列的維度: 1


In [7]:
print(f"陣列的維度大小: {a.shape}")

陣列的維度大小: (6,)


In [8]:
print(f"陣列的元素個數: {a.size}")

陣列的元素個數: 6


In [9]:
print(f"陣列的資料型態: {a.dtype}")

陣列的資料型態: int64


In [11]:
print(f"陣列的元素的佔用空間: {a.itemsize}")

陣列的元素的佔用空間: 8


In [12]:
print(f"陣列的長度: {len(a)}")

陣列的長度: 6


In [13]:
print(f"陣列的類型: {type(a)}")

陣列的類型: <class 'numpy.ndarray'>


In [14]:
b = np.random.randint(10, size=(3,4)) 

print(f'印出的結果:\n {b}')
print(f'陣列的維度:ndim → {b.ndim}')
print(f'陣列的維度大小:shape → {b.shape}')
print(f'陣列中的元素個數:size → {b.size}')
print(f'陣列中的資料型態:dtype → {b.dtype}')
print(f'陣列中的元素占用空間: itemsize → {b.itemsize}')
print(f'陣列的長度: length → {len(b)}')
print(f'陣列的類型: type → {type(b)}')

印出的結果:
 [[5 9 6 6]
 [1 9 3 8]
 [1 8 5 1]]
陣列的維度:ndim → 2
陣列的維度大小:shape → (3, 4)
陣列中的元素個數:size → 12
陣列中的資料型態:dtype → int64
陣列中的元素占用空間: itemsize → 8
陣列的長度: length → 3
陣列的類型: type → <class 'numpy.ndarray'>


In [15]:
c = np.random.randint(10, size=(2,3,2)) 

print(f'印出的結果:\n {c}')
print(f'陣列的維度:ndim → {c.ndim}')
print(f'陣列的維度大小:shape → {c.shape}')
print(f'陣列中的元素個數:size → {c.size}')
print(f'陣列中的資料型態:dtype → {c.dtype}')
print(f'陣列中的元素占用空間: itemsize → {c.itemsize}')
print(f'陣列的長度: length → {len(c)}')
print(f'陣列的類型: type → {type(c)}')

印出的結果:
 [[[4 2]
  [3 6]
  [1 6]]

 [[7 9]
  [1 6]
  [2 2]]]
陣列的維度:ndim → 3
陣列的維度大小:shape → (2, 3, 2)
陣列中的元素個數:size → 12
陣列中的資料型態:dtype → int64
陣列中的元素占用空間: itemsize → 8
陣列的長度: length → 2
陣列的類型: type → <class 'numpy.ndarray'>
