In [4]:
import numpy as np

In [5]:
print(np)

<module 'numpy' from '/home/codespace/.local/lib/python3.10/site-packages/numpy/__init__.py'>


In [7]:
print(np.__version__)

1.24.3


In [1]:
np1 = np.zeros([2, 3])

NameError: name 'np' is not defined

In [3]:
print(nb)

<module 'numpy' from '/home/codespace/.local/lib/python3.10/site-packages/numpy/__init__.py'>


In [9]:
a = np.arange(15).reshape(3,5)

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print(a.ndim)

2


In [12]:
print(a.shape)

(3, 5)


In [13]:
print(a.size)

15


In [14]:
print(a.dtype)

int64


In [16]:
print(a.itemsize)

8


In [17]:
print(a.data)

In [18]:
list(a)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [19]:
a.tolist()

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [20]:
np1 = np.array([1, 2, 3])
np2 = np.array([3, 4, 5])


In [21]:
np1+np2

array([4, 6, 8])

In [22]:
print(np1.ndim, np1.shape, np1.dtype)

1 (3,) int64


In [23]:
np3 = np.array([1,2,3,4,5,6])

In [28]:
npd = np.genfromtxt("c:\downloads\\test.csv", delimiter=',')

FileNotFoundError: c:\downloads\test.csv not found.

In [29]:
np3 = np3.reshape([2,3])

In [30]:
print(np3.ndim, np3.shape, np3.dtype)

2 (2, 3) int64


In [2]:
np1 = np.zeros([2, 3])

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np1 = np.zeros([2, 3])

In [5]:
print(np1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
np2 = np.ones([2, 3])

In [7]:
print(np2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
np3 = np.array([1,2,3,4,5,6])

In [9]:
print(np3[2])

3


In [10]:
np3 = np3.reshape([2,3])

In [11]:
print(np3[1,0])

4


In [12]:
np3 = np.array([1,2,3,4,5,6])

In [13]:
print(np3 > 3)

[False False False  True  True  True]


In [14]:
print(np3[np3 > 3])

[4 5 6]


In [15]:
print(np3[np3 > 3])

[4 5 6]
